version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rag_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rag_db
      MYSQL_USER: rag_user
      MYSQL_PASSWORD: rag_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rag_app:
    build: .
    container_name: rag_application
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: rag_user
      MYSQL_PASSWORD: rag_password
      MYSQL_DATABASE: rag_db
      GEMINI_API_KEY: AIzaSyBrzQBlC9MIU1MfqDU_hpViZ_qFR9Vggs0
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
      - ./documents:/app/documents

volumes:
  mysql_data:

